// reactjs/src/components/pages/register/index.jsx
import React, { useEffect } from "react";
import { useHistory, useNavigate } from "react-router-dom";
import { Link, useLocation } from "react-router-dom";
import "owl.carousel/dist/assets/owl.carousel.css";
import "owl.carousel/dist/assets/owl.theme.default.css";
import OwlCarousel from "react-owl-carousel";
import { LoginImg, logo, NetIcon1, NetIcon2 } from "../../imagepath";
import FeatherIcon from "feather-icons-react";
import { useState } from "react";
import * as yup from "yup";
import { useForm, Controller } from 'react-hook-form'
import { yupResolver } from '@hookform/resolvers/yup'
import "../../../assets/js/jquery-3.6.0.min.js"




const Register = (props) => {

  const [eye,seteye] = useState(true)

    const onEyeClick = () =>{
      seteye(!eye)
    }



  var settings = {
    //autoWidth: true,
    items: 2,
    margin: 25,
    dots: true,
    nav: true,
    navText: [
      '<i className="fas fa-arrow-left"></i>',
      '<i className="fas fa-arrow-right"></i>',
    ],

    loop: true,
    responsiveClass: true,
    responsive: {
      0: {
        items: 1,
      },
      768: {
        items: 1,
      },
      1170: {
        items: 1,
      },
    },
  };

  return (
    <>
      <div className="main-wrapper log-wrap">
        <div className="row">
          {/* Login Banner */}
          <div className="col-md-6 login-bg">
            <OwlCarousel
              {...settings}
              className="owl-carousel login-slide owl-theme"
            >
              <div className="welcome-login">
                <div className="login-banner">
                  <img src={LoginImg} className="img-fluid" alt="Logo" />
                </div>
                <div className="mentor-course text-center">
                  <h2>
                    Welcome to <br />
                    DreamsLMS Courses.
                  </h2>
                  <p>
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed
                    do eiusmod tempor incididunt ut labore et dolore magna
                    aliqua. Ut enim ad minim veniam.
                  </p>
                </div>
              </div>
              <div className="welcome-login">
                <div className="login-banner">
                  <img src={LoginImg} className="img-fluid" alt="Logo" />
                </div>
                <div className="mentor-course text-center">
                  <h2>
                    Welcome to <br />
                    DreamsLMS Courses.
                  </h2>
                  <p>
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed
                    do eiusmod tempor incididunt ut labore et dolore magna
                    aliqua. Ut enim ad minim veniam.
                  </p>
                </div>
              </div>
              <div className="welcome-login">
                <div className="login-banner">
                  <img src={LoginImg} className="img-fluid" alt="Logo" />
                </div>
                <div className="mentor-course text-center">
                  <h2>
                    Welcome to <br />
                    DreamsLMS Courses.
                  </h2>
                  <p>
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed
                    do eiusmod tempor incididunt ut labore et dolore magna
                    aliqua. Ut enim ad minim veniam.
                  </p>
                </div>
              </div>
            </OwlCarousel>
          </div>
          {/* /Login Banner */}
          <div className="col-md-6 login-wrap-bg">
            {/* Login */}
            <div className="login-wrapper">
              <div className="loginbox">
                <div className="img-logo">
                  <img src={logo} className="img-fluid" alt="Logo" />
                  <div className="back-home">
                    <Link to="/">Back to Home</Link>
                  </div>
                </div>
                <h1>Sign up</h1>
                <form action="/reactjs/login">
                  <div className="form-group">
                    <label className="form-control-label">Full Name</label>
                    <input
                      type="text"
                      className="form-control"
                      placeholder="Enter your Full Name"
                    />
                  </div>
                  <div className="form-group">
                    <label className="form-control-label">Email</label>
                    <input
                      type="email"
                      className="form-control"
                      placeholder="Enter your email address"
                    />
                  </div>
                  <div className="form-group">
                    <label className="form-control-label">Password</label>
                      <div className="pass-group" id="passwordInput">																	
										<input className="form-control pass-input" placeholder="Enter your password" type={eye ? "password" : "text"}/>
                    {/* <span onClick={onEyeClick} className={`fa toggle-password feather-eye" ${eye ? "fa-eye" : "fa-eye-slash" }`}/> */}
                    <span onClick={onEyeClick} className={`fa toggle-password feather-eye" ${eye ? "fa-eye" : "fa-eye-slash" }`}/>
										<span className="toggle-password feather-eye"></span>
										<span className="pass-checked"><i className="feather-check"></i></span>
									</div>
                    <div className="password-strength" id="passwordStrength">
                      <span id="poor" />
                      <span id="weak" />
                      <span id="strong" />
                      <span id="heavy" />
                    </div>
                    <div id="passwordInfo" />
                  </div>
                  <div className="form-check remember-me">
                    <label className="form-check-label mb-0">
                      <input
                        className="form-check-input"
                        type="checkbox"
                        name="remember"
                      />
                      I agree to the
                      <Link to="/term-condition">Terms of Service</Link> and
                      <Link to="/privacy-policy">Privacy Policy.</Link>
                    </label>
                  </div>
                  <div className="d-grid">
                    <button className="btn btn-primary btn-start" type="submit"
                      // onClick={() => navigate("/login")}
                    >
                      Create Account
                    </button>
                  </div>
                </form>
              </div>
              <div className="google-bg text-center">
                <span>
                  <Link to="#">Or sign in with</Link>
                </span>
                <div className="sign-google">
                  <ul>
                    <li>
                      <Link to="#">
                        <img src={NetIcon1} className="img-fluid" alt="Logo" />
                        Sign In using Google
                      </Link>
                    </li>
                    <li>
                      <Link to="#">
                        <img src={NetIcon2} className="img-fluid" alt="Logo" />
                        Sign In using Facebook
                      </Link>
                    </li>
                  </ul>
                </div>
                <p className="mb-0">
                  Already have an account? <Link to="/login">Sign in</Link>
                </p>
              </div>
            </div>
            {/* /Login */}
          </div>
        </div>
      </div>
    </>
  );
};

export default Register;

// angular/src/app/auth/register-page/register/register.component.ts
import { Component, OnInit } from '@angular/core';
import { DataService } from 'src/app/shared/service/data/data.service';
import { OwlOptions } from 'ngx-owl-carousel-o';
import { passwordResponce, register } from 'src/app/models/register.model';
import { routes } from 'src/app/shared/service/routes/routes';

@Component({
  selector: 'app-register',
  templateUrl: './register.component.html',
  styleUrls: ['./register.component.scss']
})
export class RegisterComponent implements OnInit {
  public routes = routes;
  public registerForm:register={}
  public passwordResponce:passwordResponce={};

  public register: any = [];

  password= 'password';
  show = true;

  public registerOwlOptions: OwlOptions = {
    margin: 25,
    nav: true,
    loop: true,
    responsive: {
        0: {
          items: 1
        },
        768 : {
          items: 3
        },
        1170: {
          items: 4
        }
    },
  };

  constructor(private DataService: DataService) {
    this.register = this.DataService.register;
  }

  ngOnInit(): void {
  }
  onClick() {
    if (this.password === 'password') {
      this.password = 'text';
      this.show = false;
    } else {
      this.password = 'password';
      this.show = true;
    }
  }

  public onChangePassword(password:any){
    if(password.match(/^$|\s+/)) {
      this.passwordResponce.passwordResponceText = "whitespaces are not allowed"
      this.passwordResponce.passwordResponceImage = ""
      this.passwordResponce.passwordResponceKey = ''
      return
    }
    if(password.length == 0){
      this.passwordResponce.passwordResponceText = ""
      this.passwordResponce.passwordResponceImage = ""
      this.passwordResponce.passwordResponceKey = ''
      return
    }
    if (password.length < 8) {
      this.passwordResponce.passwordResponceText = "Weak. Must contain at least 8 characters"
      this.passwordResponce.passwordResponceImage = "assets/img/icon/angry.svg"
      this.passwordResponce.passwordResponceKey = '0'
    } else if (password.search(/[a-z]/) < 0) {
      this.passwordResponce.passwordResponceText = "Average. Must contain at least 1 upper case and number"
      this.passwordResponce.passwordResponceImage = "assets/img/icon/anguish.svg"
      this.passwordResponce.passwordResponceKey = '1'
    } else if(password.search(/[A-Z]/) < 0) {
      this.passwordResponce.passwordResponceText = "Average. Must contain at least 1 upper case and number"
      this.passwordResponce.passwordResponceImage = "assets/img/icon/anguish.svg"
      this.passwordResponce.passwordResponceKey = '1'
    } else  if (password.search(/[0-9]/) < 0) {
      this.passwordResponce.passwordResponceText= "Average. Must contain at least 1 upper case and number"
      this.passwordResponce.passwordResponceImage = "assets/img/icon/anguish.svg"
      this.passwordResponce.passwordResponceKey = '1'
    } else  if (password.search(/(?=.*?[#?!@$%^&*-])/) < 0) {
      this.passwordResponce.passwordResponceText = "Almost. Must contain special symbol"
      this.passwordResponce.passwordResponceImage = "assets/img/icon/smile.svg"
      this.passwordResponce.passwordResponceKey = '2'
    }else {
      this.passwordResponce.passwordResponceText = "Awesome! You have a secure password."
        this.passwordResponce.passwordResponceImage = "assets/img/icon/smile.svg"
         this.passwordResponce.passwordResponceKey = '3'
     }
  }

}

<!-- Main Wrapper -->
<div class="main-wrapper log-wrap">
    <div class="row">
        <!-- Login Banner -->
        <div class="col-md-6 login-bg">
            <div class="row w-100">
                <div class="col-md-12">
                    <owl-carousel-o [options]="registerOwlOptions">
                        <ng-container *ngFor="let slide of register">
                            <ng-template carouselSlide>
                                <div class="welcome-login">
                                    <div class="login-banner">
                                        <img [src]="slide.img" class="img-fluid" alt="Logo" />
                                    </div>
                                    <div class="mentor-course text-center">
                                        <h2>{{ slide.content1 }}<br />{{ slide.content2 }}</h2>
                                        <p>{{ slide.paragraph }}</p>
                                    </div>
                                </div>
                            </ng-template>
                        </ng-container>
                    </owl-carousel-o>
                </div>
            </div>
        </div>
        <!-- /Login Banner -->

        <div class="col-md-6 login-wrap-bg">
            <!-- Login -->
            <div class="login-wrapper">
                <div class="loginbox">
                    <div class="img-logo">
                        <img src="assets/img/logo.svg" class="img-fluid" alt="Logo" />
                        <div class="back-home">
                            <a [routerLink]="routes.home">Back to Home</a>
                        </div>
                    </div>
                    <h1>Sign up</h1>
                    <div class="form-group">
                        <label class="form-control-label">Full Name</label>
                        <input type="text" class="form-control" placeholder="Enter your Full Name" />
                    </div>
                    <div class="form-group">
                        <label class="form-control-label">Email</label>
                        <input type="email" class="form-control" placeholder="Enter your email address" />
                    </div>
                    <div class="form-group">
                        <label class="form-control-label">Password</label>
                        <div class="pass-group" id="passwordInput">
                            <input [type]="password" class="form-control pass-input" placeholder="Enter your password"
                                [(ngModel)]="registerForm.password" (input)="onChangePassword(registerForm.password)" />
                            <span><i-feather name="eye" class="toggle-password feather-eye" (click)="onClick()"
                                    *ngIf="show"></i-feather></span>
                            <span><i-feather name="check" class="pass-checked" [ngClass]="{
                    active: passwordResponce.passwordResponceKey === '3'
                  }"></i-feather></span>
                            <span><i-feather name="eye-off" class="toggle-password feather-eye-off" (click)="onClick()"
                                    *ngIf="!show"></i-feather></span>
                        </div>
                        <div class="password-strength" [ngClass]="{
                'poor-active': passwordResponce.passwordResponceKey === '0',
                'avg-active': passwordResponce.passwordResponceKey === '1',
                'strong-active': passwordResponce.passwordResponceKey === '2',
                'heavy-active': passwordResponce.passwordResponceKey === '3'
              }" id="passwordStrength">
                            <span id="poor" class="active"></span>
                            <span id="weak" class="active"></span>
                            <span id="strong" class="active"></span>
                            <span id="heavy" class="active"></span>
                        </div>
                        <div id="passwordInfo" [ngClass]="{
                weak: passwordResponce.passwordResponceKey === '0',
                average: passwordResponce.passwordResponceKey === '1',
                good: passwordResponce.passwordResponceKey === '2',
                great: passwordResponce.passwordResponceKey === '3'
              }">
                            <img [src]="passwordResponce.passwordResponceImage" />
                            {{ passwordResponce.passwordResponceText }}
                        </div>
                    </div>

                    <div class="form-check remember-me">
                        <label class="form-check-label mb-0">
                            <input class="form-check-input input-box-auth" type="checkbox" name="remember" />
                            I agree to the
                            <a [routerLink]="routes.page_term_condition">Terms of Service</a> and
                            <a [routerLink]="routes.page_privacy_policy">Privacy Policy.</a>
                        </label>
                    </div>
                    <div class="d-grid">
                        <button class="btn btn-primary btn-start" type="submit" [routerLink]="routes.login">
                            Create Account
                        </button>
                    </div>
                </div>
                <div class="google-bg text-center">
                    <span><a href="javascript:;">Or sign in with</a></span>
                    <div class="sign-google">
                        <ul>
                            <li>
                                <a href="javascript:;"><img src="assets/img/net-icon-01.png" class="img-fluid"
                                        alt="Logo" />
                                    Sign In using Google</a>
                            </li>
                            <li>
                                <a href="javascript:;"><img src="assets/img/net-icon-02.png" class="img-fluid"
                                        alt="Logo" />Sign In using Facebook</a>
                            </li>
                        </ul>
                    </div>
                    <p class="mb-0">
                        Already have an account? <a [routerLink]="routes.login">Sign in</a>
                    </p>
                </div>
            </div>
            <!-- /Login -->
        </div>
    </div>
</div>
<!-- /Main Wrapper -->
