// reactjs/src/components/student/courseStudent/index.jsx
import React, { useState } from "react";
import { Link } from "react-router-dom";
import Footer from "../../footer";
import {
  Course10,
  Course11,
  Course12,
  Course13,
  Course14,
  Course15,
  Course16,
  Course17,
  User11,
} from "../../imagepath";
import StudentHeader from "../header";
import CourseMenu from "../courseMenu";
import { Search } from "react-feather";
import Select from "react-select";

export default function CourseStudent() {
  const [value, setValue] = useState(null);
  const options = [
    { label: "Newly Published", value: "new" },
    { label: "Angular", value: "1" },
    { label: "React", value: "2" },
    { label: "Node", value: "3" },
  ];
  const style = {
    control: (baseStyles, state) => ({
      ...baseStyles,
      backgroundColor: "white",
      width: "100%",
      height: "40px",
      color: "black",
      minHeight: "40px",
      border: "1px solid #e9ecef",
      paddingLeft: "5px",
      // This line disable the blue border
      boxShadow: state.isFocused ? 0 : 0,
      borderRadius: state.isSelected ? "0" : "10px",
      fontSize: "14px",
      "&:hover": {
        cursor: "pointer",
      },
      outline: "none",
    }),
    menu: (base) => ({ ...base, marginTop: "0px" }),
    menuList: (base) => ({ ...base, padding: "0" }),
    option: (provided, state) => ({
      ...provided,
      backgroundColor: state.isSelected ? "#FFDEDA" : "white",
      color: "black",
      fontSize: "14px",
      "&:hover": {
        backgroundColor: "#FFDEDA",
        // #dddddd
      },
    }),
    indicatorSeparator: (base) => ({
      ...base,
      display: "none",
    }),
    dropdownIndicator: (base, state) => ({
      ...base,
      color: "black",
      transform: state.selectProps.menuIsOpen ? "rotate(-180deg)" : "rotate(0)",
      transition: "250ms",
    }),
  };
  return (
    <div className="main-wrapper">
      <StudentHeader />
      <div className="course-student-header">
        <div className="container">
          <div className="student-group">
            <div className="course-group ">
              <div className="course-group-img d-flex">
                <Link to="/students-profile">
                  <img src={User11} alt="" className="img-fluid" />
                </Link>
                <div className="d-flex align-items-center">
                  <div className="course-name">
                    <h4>
                      <Link to="/students-profile">Rolands R</Link>
                      <span>Beginner</span>
                    </h4>
                    <p>Student</p>
                  </div>
                </div>
              </div>
              <div className="course-share ">
                <Link to="#;" className="btn btn-primary">
                  Account Settings
                </Link>
              </div>
            </div>
          </div>
          <CourseMenu activeMenu={"Courses"} />
        </div>
      </div>

      <section className="course-content">
        <div className="container">
          <div className="student-widget">
            <div className="student-widget-group">
              <div className="row">
                <div className="col-lg-12">
                  <div className="showing-list">
                    <div className="row">
                      <div className="col-lg-12">
                        <div className="show-filter choose-search-blk">
                          <form action="#">
                            <div className="mycourse-student align-items-center">
                              <div className="student-search">
                                <div className=" search-group">
                                  <Search className="searchFeather" size={16} />
                                  <input
                                    type="text"
                                    className="form-control"
                                    placeholder="Search our courses"
                                  />
                                </div>
                              </div>
                              <div className="student-filter">
                                <div className="form-group select-form mb-0">
                                  <Select
                                    className=" select country-select"
                                    name="sellist1"
                                    options={options}
                                    defaultValue={options[0]}
                                    placeholder="Choose"
                                    onChange={setValue}
                                    styles={style}
                                  ></Select>
                                </div>
                              </div>
                            </div>
                          </form>
                        </div>
                      </div>
                    </div>
                  </div>

                  <div className="row">
                    <div className="col-xl-3 col-lg-4 col-md-6 d-flex">
                      <div className="course-box course-design d-flex ">
                        <div className="product">
                          <div className="product-img">
                            <Link to="course-details">
                              <img
                                className="img-fluid"
                                alt=""
                                src={Course10}
                              />
                            </Link>
                          </div>
                          <div className="product-content">
                            <h3 className="title">
                              <Link to="course-details">
                                Information About UI/UX Design Degree
                              </Link>
                            </h3>
                            <div className="rating-student">
                              <div className="rating">
                                <i className="fas fa-star filled"></i>
                                <i className="fas fa-star filled"></i>
                                <i className="fas fa-star filled"></i>
                                <i className="fas fa-star filled"></i>
                                <i className="fas fa-star"></i>
                                <span className="d-inline-block average-rating">
                                  <span>4.0</span>
                                </span>
                              </div>
                              <div className="edit-rate">
                                <Link to="#;">Edit rating</Link>
                              </div>
                            </div>
                            <div className="progress-stip">
                              <div className="progress-bar bg-success progress-bar-striped active-stip"></div>
                            </div>
                            <div className="student-percent">
                              <p>35% Completed</p>
                            </div>
                            <div className="start-leason hoverBlue d-flex align-items-center">
                              <Link
                                to="course-lesson"
                                className="btn btn-primary"
                              >
                                Start Lesson
                              </Link>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                    <div className="col-xl-3 col-lg-4 col-md-6 d-flex">
                      <div className="course-box course-design d-flex ">
                        <div className="product">
                          <div className="product-img">
                            <Link to="course-details">
                              <img
                                className="img-fluid"
                                alt=""
                                src={Course11}
                              />
                            </Link>
                          </div>
                          <div className="product-content">
                            <h3 className="title">
                              <Link to="course-details">
                                Wordpress for Beginners - Master Wordpress
                                Quickly
                              </Link>
                            </h3>
                            <div className="rating-student">
                              <div className="rating">
                                <i className="fas fa-star filled"></i>
                                <i className="fas fa-star filled"></i>
                                <i className="fas fa-star filled"></i>
                                <i className="fas fa-star filled"></i>
                                <i className="fas fa-star"></i>
                                <span className="d-inline-block average-rating">
                                  <span>4.0</span>{" "}
                                </span>
                              </div>
                              <div className="edit-rate">
                                <Link to="#;">Edit rating</Link>
                              </div>
                            </div>
                            <div className="progress-stip">
                              <div className="progress-bar bg-success progress-bar-striped "></div>
                            </div>
                            <div className="student-percent">
                              <p>0% Completed</p>
                            </div>
                            <div className="start-leason hoverBlue d-flex align-items-center">
                              <Link
                                to="course-lesson"
                                className="btn btn-primary"
                              >
                                Start Lesson
                              </Link>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                    <div className="col-xl-3 col-lg-4 col-md-6 d-flex">
                      <div className="course-box course-design d-flex ">
                        <div className="product">
                          <div className="product-img">
                            <Link to="course-details">
                              <img
                                className="img-fluid"
                                alt=""
                                src={Course12}
                              />
                            </Link>
                          </div>
                          <div className="product-content">
                            <h3 className="title">
                              <Link to="course-details">
                                Sketch from A to Z (2022): Become an app
                                designer
                              </Link>
                            </h3>
                            <div className="rating-student">
                              <div className="rating">
                                <i className="fas fa-star filled"></i>
                                <i className="fas fa-star filled"></i>
                                <i className="fas fa-star filled"></i>
                                <i className="fas fa-star filled"></i>
                                <i className="fas fa-star"></i>
                                <span className="d-inline-block average-rating">
                                  <span>4.0</span>
                                </span>
                              </div>
                              <div className="edit-rate">
                                <Link to="#;">Edit rating</Link>
                              </div>
                            </div>
                            <div className="progress-stip">
                              <div className="progress-bar bg-success progress-bar-striped"></div>
                            </div>
                            <div className="student-percent">
                              <p>0% Completed</p>
                            </div>
                            <div className="start-leason hoverBlue d-flex align-items-center">
                              <Link
                                to="course-lesson"
                                className="btn btn-primary"
                              >
                                Start Lesson
                              </Link>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                    <div className="col-xl-3 col-lg-4 col-md-6 d-flex">
                      <div className="course-box course-design d-flex ">
                        <div className="product">
                          <div className="product-img">
                            <Link to="course-details">
                              <img
                                className="img-fluid"
                                alt=""
                                src={Course13}
                              />
                            </Link>
                          </div>
                          <div className="product-content">
                            <h3 className="title">
                              <Link to="course-details">
                                Learn Angular Fundamentals From ...
                              </Link>
                            </h3>
                            <div className="rating-student">
                              <div className="rating">
                                <i className="fas fa-star filled"></i>
                                <i className="fas fa-star filled"></i>
                                <i className="fas fa-star filled"></i>
                                <i className="fas fa-star filled"></i>
                                <i className="fas fa-star"></i>
                                <span className="d-inline-block average-rating">
                                  <span>4.0</span>
                                </span>
                              </div>
                              <div className="edit-rate">
                                <Link to="#;">Edit rating</Link>
                              </div>
                            </div>
                            <div className="progress-stip">
                              <div className="progress-bar bg-success progress-bar-striped "></div>
                            </div>
                            <div className="student-percent">
                              <p>0% Completed</p>
                            </div>
                            <div className="start-leason hoverBlue d-flex align-items-center">
                              <Link
                                to="course-lesson"
                                className="btn btn-primary"
                              >
                                Start Lesson
                              </Link>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                    <div className="col-xl-3 col-lg-4 col-md-6 d-flex">
                      <div className="course-box course-design d-flex ">
                        <div className="product">
                          <div className="product-img">
                            <Link to="course-details">
                              <img
                                className="img-fluid"
                                alt=""
                                src={Course14}
                              />
                            </Link>
                          </div>
                          <div className="product-content">
                            <h3 className="title">
                              <Link to="course-details">
                                Build Responsive Real World Websites with...
                              </Link>
                            </h3>
                            <div className="rating-student">
                              <div className="rating">
                                <i className="fas fa-star filled"></i>
                                <i className="fas fa-star filled"></i>
                                <i className="fas fa-star filled"></i>
                                <i className="fas fa-star filled"></i>
                                <i className="fas fa-star"></i>
                                <span className="d-inline-block average-rating">
                                  <span>4.0</span>
                                </span>
                              </div>
                              <div className="edit-rate">
                                <Link to="#;">Edit rating</Link>
                              </div>
                            </div>
                            <div className="progress-stip">
                              <div className="progress-bar bg-success progress-bar-striped "></div>
                            </div>
                            <div className="student-percent">
                              <p>0% Completed</p>
                            </div>
                            <div className="start-leason hoverBlue d-flex align-items-center">
                              <Link
                                to="course-lesson"
                                className="btn btn-primary"
                              >
                                Start Lesson
                              </Link>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                    <div className="col-xl-3 col-lg-4 col-md-6 d-flex">
                      <div className="course-box course-design d-flex ">
                        <div className="product">
                          <div className="product-img">
                            <Link to="course-details">
                              <img
                                className="img-fluid"
                                alt=""
                                src={Course15}
                              />
                            </Link>
                          </div>
                          <div className="product-content">
                            <h3 className="title">
                              <Link to="course-details">
                                C# Developers Double Your Coding Speed with ...
                              </Link>
                            </h3>
                            <div className="rating-student">
                              <div className="rating">
                                <i className="fas fa-star filled"></i>
                                <i className="fas fa-star filled"></i>
                                <i className="fas fa-star filled"></i>
                                <i className="fas fa-star filled"></i>
                                <i className="fas fa-star"></i>
                                <span className="d-inline-block average-rating">
                                  <span>4.0</span>
                                </span>
                              </div>
                              <div className="edit-rate">
                                <Link to="#;">Edit rating</Link>
                              </div>
                            </div>
                            <div className="progress-stip">
                              <div className="progress-bar bg-success progress-bar-striped "></div>
                            </div>
                            <div className="student-percent">
                              <p>0% Completed</p>
                            </div>
                            <div className="start-leason hoverBlue d-flex align-items-center">
                              <Link
                                to="course-lesson"
                                className="btn btn-primary"
                              >
                                Start Lesson
                              </Link>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                    <div className="col-xl-3 col-lg-4 col-md-6 d-flex">
                      <div className="course-box course-design d-flex ">
                        <div className="product">
                          <div className="product-img">
                            <Link to="course-details">
                              <img
                                className="img-fluid"
                                alt=""
                                src={Course16}
                              />
                            </Link>
                          </div>
                          <div className="product-content">
                            <h3 className="title">
                              <Link to="course-details">
                                Learn JavaScript and Express to become a ...
                              </Link>
                            </h3>
                            <div className="rating-student">
                              <div className="rating">
                                <i className="fas fa-star filled"></i>
                                <i className="fas fa-star filled"></i>
                                <i className="fas fa-star filled"></i>
                                <i className="fas fa-star filled"></i>
                                <i className="fas fa-star"></i>
                                <span className="d-inline-block average-rating">
                                  <span>4.0</span>
                                </span>
                              </div>
                              <div className="edit-rate">
                                <Link to="#;">Edit rating</Link>
                              </div>
                            </div>
                            <div className="progress-stip">
                              <div className="progress-bar bg-success progress-bar-striped "></div>
                            </div>
                            <div className="student-percent">
                              <p>0% Completed</p>
                            </div>
                            <div className="start-leason hoverBlue d-flex align-items-center">
                              <Link
                                to="course-lesson"
                                className="btn btn-primary"
                              >
                                Start Lesson
                              </Link>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                    <div className="col-xl-3 col-lg-4 col-md-6 d-flex">
                      <div className="course-box course-design d-flex ">
                        <div className="product">
                          <div className="product-img">
                            <Link to="course-details">
                              <img
                                className="img-fluid"
                                alt=""
                                src={Course17}
                              />
                            </Link>
                          </div>
                          <div className="product-content">
                            <h3 className="title">
                              <Link to="course-details">
                                Responsive Web Design Essentials HTML5 CSS3 ...
                              </Link>
                            </h3>
                            <div className="rating-student">
                              <div className="rating">
                                <i className="fas fa-star filled"></i>
                                <i className="fas fa-star filled"></i>
                                <i className="fas fa-star filled"></i>
                                <i className="fas fa-star filled"></i>
                                <i className="fas fa-star"></i>
                                <span className="d-inline-block average-rating">
                                  <span>4.0</span>
                                </span>
                              </div>
                              <div className="edit-rate">
                                <Link id="edit-rating">Edit rating</Link>
                              </div>
                            </div>
                            <div className="publish-rate">
                              <form action="#">
                                <select className="form-select" name="sellist1">
                                  <option>4 Out of 5</option>
                                  <option>3 Out of 5</option>
                                  <option>2 Out of 5</option>
                                  <option>1 Out of 5</option>
                                </select>
                                <div className="form-group mt-3">
                                  <textarea
                                    className="form-control"
                                    rows="4"
                                    name="text"
                                  ></textarea>
                                </div>
                                <div className="group-btn mb-3">
                                  <button
                                    type="submit"
                                    className="btn btn-primary publish-btn mb-3"
                                  >
                                    Publish Rating
                                  </button>
                                  <button
                                    type="submit"
                                    className="btn btn-primary cancel-btn"
                                  >
                                    Cancel
                                  </button>
                                </div>
                              </form>
                            </div>
                            <div className="stip-grp">
                              <div className="progress-stip">
                                <div className="progress-bar bg-success progress-bar-striped "></div>
                              </div>
                              <div className="student-percent">
                                <p>0% Completed</p>
                              </div>
                              <div className="start-leason hoverBlue d-flex align-items-center">
                                <Link
                                  to="course-lesson"
                                  className="btn btn-primary"
                                >
                                  Start Lesson
                                </Link>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
      <Footer />
    </div>
  );
}

// vuejs/src/views/pages/student/course-student.vue
<template>
    <!-- Main Wrapper -->
    <div class="main-wrapper">
        
        <layouts></layouts>
			<courseheader></courseheader>
            <!-- My Course -->
			<section class="course-content">
				<div class="container">
					<div class="student-widget">
						<div class="student-widget-group">
							<div class="row">
								<div class="col-lg-12">
								
									<studentfilter></studentfilter>
									
									<div class="row">
										<div class="col-xl-3 col-lg-4 col-md-6 d-flex">
											<div class="course-box course-design d-flex " >
												<div class="product">
													<div class="product-img">
														<router-link to="course-details">
															<img class="img-fluid" alt="" src="../../../assets/img/course/course-10.jpg">
														</router-link>
													</div>
													<div class="product-content">
														<h3 class="title"><router-link to="course-details">Information About UI/UX Design Degree</router-link></h3>
														<div class="rating-student">							
															<div class="rating">							
																<i class="fas fa-star filled me-1"></i>
																<i class="fas fa-star filled me-1"></i>
																<i class="fas fa-star filled me-1"></i>
																<i class="fas fa-star filled me-1"></i>
																<i class="fas fa-star me-1"></i>
																<span class="d-inline-block average-rating"><span>4.0</span></span>
															</div>
															<div class="edit-rate">
																<a href="javascript:;">Edit rating</a>
															</div>
														</div>
														<div class="progress-stip">
															<div class="progress-bar bg-success progress-bar-striped active-stip" ></div>
														</div>
														<div class="student-percent">
															<p>35% Completed</p>
														</div>
														<div class="start-leason d-flex align-items-center">
															<router-link to="course-lesson" class="btn btn-primary">Start Lesson</router-link>
														</div>
													</div>
												</div>
											</div>
										</div>
										<div class="col-xl-3 col-lg-4 col-md-6 d-flex">
											<div class="course-box course-design d-flex " >
												<div class="product">
													<div class="product-img">
														<router-link to="course-details">
															<img class="img-fluid" alt="" src="../../../assets/img/course/course-11.jpg">
														</router-link>
													</div>
													<div class="product-content">
														<h3 class="title"><router-link to="course-details">Wordpress for Beginners - Master Wordpress Quickly</router-link></h3>
														<div class="rating-student">							
															<div class="rating">							
																<i class="fas fa-star filled me-1"></i>
																<i class="fas fa-star filled me-1"></i>
																<i class="fas fa-star filled me-1"></i>
																<i class="fas fa-star filled me-1"></i>
																<i class="fas fa-star me-1"></i>
																<span class="d-inline-block average-rating"><span>4.0</span> </span>
															</div>
															<div class="edit-rate">
																<a href="javascript:;">Edit rating</a>
															</div>
														</div>
														<div class="progress-stip">
															<div class="progress-bar bg-success progress-bar-striped " ></div>
														</div>
														<div class="student-percent">
															<p>0% Completed</p>
														</div>
														<div class="start-leason d-flex align-items-center">
															<router-link to="course-lesson" class="btn btn-primary">Start Lesson</router-link>
														</div>
													</div>
												</div>
											</div>
										</div>
										<div class="col-xl-3 col-lg-4 col-md-6 d-flex">
											<div class="course-box course-design d-flex " >
												<div class="product">
													<div class="product-img">
														<router-link to="course-details">
															<img class="img-fluid" alt="" src="../../../assets/img/course/course-12.jpg">
														</router-link>
													</div>
													<div class="product-content">
														<h3 class="title"><router-link to="course-details">Sketch from A to Z (2022): Become an app designer</router-link></h3>
														<div class="rating-student">							
															<div class="rating">							
																<i class="fas fa-star filled me-1"></i>
																<i class="fas fa-star filled me-1"></i>
																<i class="fas fa-star filled me-1"></i>
																<i class="fas fa-star filled me-1"></i>
																<i class="fas fa-star me-1"></i>
																<span class="d-inline-block average-rating"><span>4.0</span></span>
															</div>
															<div class="edit-rate">
																<a href="javascript:;">Edit rating</a>
															</div>
														</div>
														<div class="progress-stip">
															<div class="progress-bar bg-success progress-bar-striped" ></div>
														</div>
														<div class="student-percent">
															<p>0% Completed</p>
														</div>
														<div class="start-leason d-flex align-items-center">
															<router-link to="course-lesson" class="btn btn-primary">Start Lesson</router-link>
														</div>
													</div>
												</div>
											</div>
										</div>
										<div class="col-xl-3 col-lg-4 col-md-6 d-flex">
											<div class="course-box course-design d-flex " >
												<div class="product">
													<div class="product-img">
														<router-link to="course-details">
															<img class="img-fluid" alt="" src="../../../assets/img/course/course-13.jpg">
														</router-link>
													</div>
													<div class="product-content">
														<h3 class="title"><router-link to="course-details">Learn Angular Fundamentals From ...</router-link></h3>
														<div class="rating-student">							
															<div class="rating">							
																<i class="fas fa-star filled me-1"></i>
																<i class="fas fa-star filled me-1"></i>
																<i class="fas fa-star filled me-1"></i>
																<i class="fas fa-star filled me-1"></i>
																<i class="fas fa-star me-1"></i>
																<span class="d-inline-block average-rating"><span>4.0</span></span>
															</div>
															<div class="edit-rate">
																<a href="javascript:;">Edit rating</a>
															</div>
														</div>
														<div class="progress-stip">
															<div class="progress-bar bg-success progress-bar-striped " ></div>
														</div>
														<div class="student-percent">
															<p>0% Completed</p>
														</div>
														<div class="start-leason d-flex align-items-center">
															<router-link to="course-lesson" class="btn btn-primary">Start Lesson</router-link>
														</div>
													</div>
												</div>
											</div>
										</div>
										<div class="col-xl-3 col-lg-4 col-md-6 d-flex">
											<div class="course-box course-design d-flex " >
												<div class="product">
													<div class="product-img">
														<router-link to="course-details">
															<img class="img-fluid" alt="" src="../../../assets/img/course/course-14.jpg">
														</router-link>
													</div>
													<div class="product-content">
														<h3 class="title"><router-link to="course-details">Build Responsive Real World Websites with...</router-link></h3>
														<div class="rating-student">							
															<div class="rating">							
																<i class="fas fa-star filled me-1"></i>
																<i class="fas fa-star filled me-1"></i>
																<i class="fas fa-star filled me-1"></i>
																<i class="fas fa-star filled me-1"></i>
																<i class="fas fa-star me-1"></i>
																<span class="d-inline-block average-rating"><span>4.0</span></span>
															</div>
															<div class="edit-rate">
																<a href="javascript:;">Edit rating</a>
															</div>
														</div>
														<div class="progress-stip">
															<div class="progress-bar bg-success progress-bar-striped " ></div>
														</div>
														<div class="student-percent">
															<p>0% Completed</p>
														</div>
														<div class="start-leason d-flex align-items-center">
															<router-link to="course-lesson" class="btn btn-primary">Start Lesson</router-link>
														</div>
													</div>
												</div>
											</div>
										</div>
										<div class="col-xl-3 col-lg-4 col-md-6 d-flex">
											<div class="course-box course-design d-flex " >
												<div class="product">
													<div class="product-img">
														<router-link to="course-details">
															<img class="img-fluid" alt="" src="../../../assets/img/course/course-15.jpg">
														</router-link>
													</div>
													<div class="product-content">
														<h3 class="title"><router-link to="course-details">C# Developers Double Your Coding Speed with ...</router-link></h3>
														<div class="rating-student">							
															<div class="rating">							
																<i class="fas fa-star filled me-1"></i>
																<i class="fas fa-star filled me-1"></i>
																<i class="fas fa-star filled me-1"></i>
																<i class="fas fa-star filled me-1"></i>
																<i class="fas fa-star me-1"></i>
																<span class="d-inline-block average-rating"><span>4.0</span></span>
															</div>
															<div class="edit-rate">
																<a href="javascript:;">Edit rating</a>
															</div>
														</div>
														<div class="progress-stip">
															<div class="progress-bar bg-success progress-bar-striped " ></div>
														</div>
														<div class="student-percent">
															<p>0% Completed</p>
														</div>
														<div class="start-leason d-flex align-items-center">
															<router-link to="course-lesson" class="btn btn-primary">Start Lesson</router-link>
														</div>
													</div>
												</div>
											</div>
										</div>
										<div class="col-xl-3 col-lg-4 col-md-6 d-flex">
											<div class="course-box course-design d-flex " >
												<div class="product">
													<div class="product-img">
														<router-link to="course-details">
															<img class="img-fluid" alt="" src="../../../assets/img/course/course-16.jpg">
														</router-link>
													</div>
													<div class="product-content">
														<h3 class="title"><router-link to="course-details">Learn JavaScript and Express to become a ...</router-link></h3>
														<div class="rating-student">							
															<div class="rating">							
																<i class="fas fa-star filled me-1"></i>
																<i class="fas fa-star filled me-1"></i>
																<i class="fas fa-star filled me-1"></i>
																<i class="fas fa-star filled me-1"></i>
																<i class="fas fa-star me-1"></i>
																<span class="d-inline-block average-rating"><span>4.0</span></span>
															</div>
															<div class="edit-rate">
																<a href="javascript:;">Edit rating</a>
															</div>
														</div>
														<div class="progress-stip">
															<div class="progress-bar bg-success progress-bar-striped " ></div>
														</div>
														<div class="student-percent">
															<p>0% Completed</p>
														</div>
														<div class="start-leason d-flex align-items-center">
															<router-link to="course-lesson" class="btn btn-primary">Start Lesson</router-link>
														</div>
													</div>
												</div>
											</div>
										</div>
										<div class="col-xl-3 col-lg-4 col-md-6 d-flex">
											<div class="course-box course-design d-flex " >
												<div class="product">
													<div class="product-img">
														<router-link to="course-details">
															<img class="img-fluid" alt="" src="../../../assets/img/course/course-17.jpg">
														</router-link>
													</div>
													<div class="product-content">
														<h3 class="title"><router-link to="course-details">Responsive Web Design Essentials HTML5 CSS3 ...</router-link></h3>
														<div class="rating-student">							
															<div class="rating">							
																<i class="fas fa-star filled me-1"></i>
																<i class="fas fa-star filled me-1"></i>
																<i class="fas fa-star filled me-1"></i>
																<i class="fas fa-star filled me-1"></i>
																<i class="fas fa-star me-1"></i>
																<span class="d-inline-block average-rating"><span>4.0</span></span>
															</div>
															<div class="edit-rate">
																<a  id="edit-rating">Edit rating</a>
															</div>
														</div>
														<div class="publish-rate">
															<form action="#">
																<vue-select :options="Out" placeholder="4 Out of 5" name="sellist1" />
																<div class="form-group mt-3">
																	<textarea class="form-control" rows="4" name="text"></textarea>
																</div>
																<div class="group-btn mb-3">
																	<button type="submit" class="btn btn-primary publish-btn mb-3">Publish Rating</button>
																	<button type="submit" class="btn btn-primary cancel-btn">Cancel</button>
																</div>
															</form>
														</div>
														<div class="stip-grp">
															<div class="progress-stip">
																<div class="progress-bar bg-success progress-bar-striped " ></div>
															</div>
															<div class="student-percent">
																<p>0% Completed</p>
															</div>
															<div class="start-leason d-flex align-items-center">
																<router-link to="course-lesson" class="btn btn-primary">Start Lesson</router-link>
															</div>
														</div>
													</div>
												</div>
											</div>
										</div>
									</div>
									
								</div>
							</div>
						</div>
					</div>
				</div>
			</section>
			<!-- /My Course -->
        
        <layouts1></layouts1>
       
    </div>
    <!-- /Main Wrapper -->
</template>
<script>
    import Vue from 'vue'
    export default {
      components: {
       
      },
	  data() {
            return {
                Out: ["4 Out of 5", "3 Out of 5", "2 Out of 5", "1 Out of 5"],
            }
        },

		mounted() {
       
      },
      methods: {
       
    },
    }
  </Script>
