// angular/src/app/auth/login/login.component.ts
import { Component, OnInit } from '@angular/core';
import { OwlOptions } from 'ngx-owl-carousel-o';
import { DataService } from 'src/app/shared/service/data/data.service';
import { Router } from '@angular/router';
import { routes } from 'src/app/shared/service/routes/routes';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.scss'],
})
export class LoginComponent implements OnInit {
  public routes = routes;
  password= 'password';
  show = true;

  public welcomeLogin: any = [];

  public welcomeLoginOwlOptions: OwlOptions = {
    margin: 25,
    nav: true,
    loop: true,
    responsive: {
        0: {
          items: 1
        },
        768 : {
          items: 3
        },
        1170: {
          items: 4
        }
    },
  };

  constructor(private DataService: DataService, public router: Router) {
    this.welcomeLogin = this.DataService.welcomeLogin;
  }

  ngOnInit(): void {}

  onClick() {
    if (this.password === 'password') {
      this.password = 'text';
      this.show = false;
    } else {
      this.password = 'password';
      this.show = true;
    }
  }
  directIndex() {
    this.router.navigate(['/instructor/instructor-dashboard']);
  }
}

<!-- Main Wrapper -->
<div class="main-wrapper log-wrap">

    <div class="row">

        <!-- Login Banner -->
				<div class="col-md-6 login-bg">
                    <div class="row w-100">
                        <div class="col-md-12">
                            <owl-carousel-o [options]="welcomeLoginOwlOptions">
                                <ng-container *ngFor="let slide of welcomeLogin">
                                    <ng-template carouselSlide>
                                        <div class="welcome-login">
                                            <div class="login-banner">
                                                <img [src]="slide.img" class="img-fluid" alt="Logo">
                                            </div>
                                            <div class="mentor-course text-center">
                                                <h2>{{slide.content1}}<br>{{slide.content2}}</h2>
                                                <p>{{slide.paragraph}}</p>
                                            </div>
                                        </div>
                                    </ng-template>
                                </ng-container>
                            </owl-carousel-o>
                        </div>

                    </div>
				</div>
				<!-- /Login Banner -->

        <div class="col-md-6 login-wrap-bg">

            <!-- Login -->
            <div class="login-wrapper">
                <div class="loginbox">
                    <div class="w-100">
                        <div class="img-logo">
                            <img src="assets/img/logo.svg" class="img-fluid" alt="Logo">
                            <div class="back-home">
                                <a [routerLink]="routes.home">Back to Home</a>
                            </div>
                        </div>
                        <h1>Sign into Your Account</h1>
                            <div class="form-group">
                                <label class="form-control-label">Email</label>
                                <input type="email" class="form-control" placeholder="Enter your email address">
                            </div>
                            <div class="form-group">
                                <label class="form-control-label">Password</label>
                                <div class="pass-group">
                                    <input [type]="password" class="form-control pass-input" placeholder="Enter your password">
                                    <span><i-feather name="eye" class="toggle-password feather-eye" (click)="onClick()" *ngIf="show"></i-feather></span>
                                    <span><i-feather name="eye-off" class="toggle-password feather-eye-off" (click)="onClick()" *ngIf="!show"></i-feather></span>
                                </div>
                            </div>
                            <div class="forgot">
                                <span><a class="forgot-link" [routerLink]="routes.forgot_password">Forgot Password ?</a></span>
                            </div>
                            <div class="form-check remember-me">
                                <label class="form-check-label mb-0"> Remember me
                                    <input class="form-check-input input-box" type="checkbox" name="radio">
                                </label>
                            </div>
                            <div class="d-grid">
                                <button class="btn btn-primary btn-start" type="submit" (click)="directIndex()">Sign In</button>
                            </div>
                    </div>
                </div>
                <div class="google-bg text-center">
                    <span><a href="javascript:;">Or sign in with</a></span>
                    <div class="sign-google">
                        <ul>
                            <li><a href="javascript:;"><img src="assets/img/net-icon-01.png" class="img-fluid" alt="Logo"> Sign In using Google</a></li>
                            <li><a href="javascript:;"><img src="assets/img/net-icon-02.png" class="img-fluid" alt="Logo">Sign In using Facebook</a></li>
                        </ul>
                    </div>
                    <p class="mb-0">New User ? <a [routerLink]="routes.register">Create an Account</a></p>
                </div>
            </div>
            <!-- /Login -->

        </div>

    </div>

</div>
<!-- /Main Wrapper -->

// vuejs/src/views/pages/pages/login.vue
<template>
    <!-- Main Wrapper -->
    <div class="main-wrapper">
       
        <div class="row">
			
            <loginbanner></loginbanner>
            
            <div class="col-md-6 login-wrap-bg">		
            
                <!-- Login -->
                <div class="login-wrapper">
                    <div class="loginbox">
                        <div class="w-100">
                            <div class="img-logo">
                                <img src="../../../assets/img/logo.svg" class="img-fluid" alt="Logo">
                                <div class="back-home">
                                    <router-link to="/">Back to Home</router-link>
                                </div>
                            </div>
                            <h1>Sign into Your Account</h1>
                            <form action="instructor-dashboard">
                                <div class="form-group">
                                    <label class="form-control-label">Email</label>
                                    <input type="email" class="form-control" placeholder="Enter your email address">
                                </div>
                                <div class="form-group">
                                    <label class="form-control-label">Password</label>
                                    <div class="pass-group">
                                        <input type="password" class="form-control pass-input" placeholder="Enter your password">
                                        <span class="feather-eye toggle-password"></span>
                                    </div>
                                </div>
                                <div class="forgot">
                                    <span><router-link class="forgot-link" to="forgot-password">Forgot Password ?</router-link></span>
                                </div>
                                <div class="remember-me">
                                    <label class="custom_check mr-2 mb-0 d-inline-flex remember-me"> Remember me  
                                        <input type="checkbox" name="radio">
                                        <span class="checkmark"></span>
                                    </label>
                                </div>
                                <div class="d-grid">
                                    <button class="btn btn-primary btn-start" type="submit">Sign In</button>
                                </div>
                            </form>
                        </div>
                    </div>
                    <div class="google-bg text-center">
                        <span><a href="javascript:void(0);">Or sign in with</a></span>
                        <div class="sign-google">
                            <ul>
                                <li><a href="javascript:void(0);"><img src="../../../assets/img/net-icon-01.png" class="img-fluid" alt="Logo"> Sign In using Google</a></li>
                                <li><a href="javascript:void(0);"><img src="../../../assets/img/net-icon-02.png" class="img-fluid" alt="Logo">Sign In using Facebook</a></li>
                            </ul>
                        </div>
                        <p class="mb-0">New User ? <router-link to="register">Create an Account</router-link></p>
                    </div>
                </div>
                <!-- /Login -->
                
            </div>
            
        </div>
    </div>
    <!-- /Main Wrapper -->
</template>
<script>
    import Vue from 'vue'
    export default {
      computed:{
           
        },
      data() {
            return {
                
               
            }
        },
        mounted() {
            if($('.toggle-password').length > 0) {
		$(document).on('click', '.toggle-password', function() {
			$(this).toggleClass("feather-eye feather-eye-off");
			var input = $(".pass-input");
			if (input.attr("type") == "password") {
				input.attr("type", "text");
			} else {
				input.attr("type", "password");
			}
		});
	}
        }
    }
</script>
