// angular/src/app/auth/verification-code/verification-code.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { OwlOptions } from 'ngx-owl-carousel-o';
import { DataService } from 'src/app/shared/service/data/data.service';
import { routes } from 'src/app/shared/service/routes/routes';

@Component({
  selector: 'app-verification-code',
  templateUrl: './verification-code.component.html',
  styleUrls: ['./verification-code.component.scss']
})
export class VerificationCodeComponent implements OnInit {
  public verificationCode: any = [];
  public routes = routes;
  public oneTimePassword = {
    data1: "",
    data2: "",
    data3: "",
    data4: ""
  };
  public verificationCodeOwlOptions: OwlOptions = {
    margin: 24,
    nav: true,
    loop: true,
    responsive: {
      0: {
        items: 1,
      },
      768: {
        items: 1,
      },
      1170: {
        items: 1,
      },
    },
  };

  public ValueChanged(data: string, box: string): void {
    if (box == 'digit-1' && data.length > 0) {
      document.getElementById('digit-2')?.focus();
    } else if (box == 'digit-2' && data.length > 0) {
      document.getElementById('digit-3')?.focus();
    } else if (box == 'digit-3' && data.length > 0) {
      document.getElementById('digit-4')?.focus();
    } else {
      return
    }
  }
  public tiggerBackspace(data: any, box: string) {
    let StringyfyData: any;
    if (data) {
      StringyfyData = data.toString();
    } else {
      StringyfyData = null;
    }
    if (box == 'digit-4' && StringyfyData == null) {
      document.getElementById('digit-3')?.focus();
    } else if (box == 'digit-3' && StringyfyData == null) {
      document.getElementById('digit-2')?.focus();
    } else if (box == 'digit-2' && StringyfyData == null) {
      document.getElementById('digit-1')?.focus();
    }
  }


  constructor(private DataService: DataService,public router: Router) {
    this.verificationCode = this.DataService.verificationCode;
  }

  ngOnInit(): void {
  }
  directLogin() {
    this.router.navigate(['/auth/login']);
  }
}

<!-- Login Banner -->
<div class="col-md-6 login-bg">
    <div class="row w-100">
        <div class="col-md-12">
            <owl-carousel-o [options]="verificationCodeOwlOptions">
                <ng-container *ngFor="let slide of verificationCode">
                    <ng-template carouselSlide>
                        <div class="welcome-login">
                            <div class="login-banner">
                                <img [src]="slide.img" class="img-fluid" alt="Logo">
                            </div>
                            <div class="mentor-course text-center">
                                <h2>{{slide.content1}}<br>{{slide.content2}}</h2>
                                <p>{{slide.paragraph}}</p>
                            </div>
                        </div>
                    </ng-template>
                </ng-container>
            </owl-carousel-o>
        </div>

    </div>
</div>
<!-- /Login Banner -->

<div class="col-md-6 login-wrap-bg">

    <!-- Login -->
    <div class="login-wrapper">
        <div class="loginbox">
            <div class="img-logo">
                <img src="assets/img/logo.svg" class="img-fluid" alt="Logo">
                <div class="back-home">
                    <a [routerLink]="routes.home">Back to Home</a>
                </div>
            </div>
            <h1>Enter Varification Code</h1>
            <div class="reset-password">
                <p>We have just sent a verification code to your registed email id</p>
            </div>
            <div class="verification-code">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="d-flex digit-group">
                            <input [(ngModel)]="oneTimePassword.data1" maxlength="1" (keydown.backspace)="tiggerBackspace(oneTimePassword.data1 , 'digit-1')" (input)="ValueChanged(oneTimePassword.data1 , 'digit-1')" type="text" class="form-control" id="digit-1" name="digit-1"  value="8" />
                            <input [(ngModel)]="oneTimePassword.data2" maxlength="1" (keydown.backspace)="tiggerBackspace(oneTimePassword.data2 , 'digit-2')" (input)="ValueChanged(oneTimePassword.data2 , 'digit-2')" type="text" class="form-control" id="digit-2" name="digit-2"   />
                            <input [(ngModel)]="oneTimePassword.data3" maxlength="1" (keydown.backspace)="tiggerBackspace(oneTimePassword.data3 , 'digit-3')" (input)="ValueChanged(oneTimePassword.data3 , 'digit-3')" type="text" class="form-control" id="digit-3" name="digit-3"   />
                            <input [(ngModel)]="oneTimePassword.data4" maxlength="1" (keydown.backspace)="tiggerBackspace(oneTimePassword.data4 , 'digit-4')"  (input)="ValueChanged(oneTimePassword.data4 , 'digit-4')" type="text"  class="form-control" id="digit-4" name="digit-4"   />
                        </div>
                    </div>
                    <div class="send-code">
                        <a [routerLink]="routes.page_verification_code ">Send the code again</a>
                    </div>
                    <div class="d-grid">
                        <button class="btn btn-primary btn-start" type="submit" (click)="directLogin()">Submit</button>
                    </div>
                </div>
              </div>
        </div>
    </div>
    <!-- /Login -->

</div>

// vuejs/src/views/pages/pages/verification-code.vue
<template>
    <!-- Main Wrapper -->
    <div class="main-wrapper">
       
        <div class="row">
			
            <loginbanner></loginbanner>
            
            <div class="col-md-6 login-wrap-bg">		
				
                <!-- Login -->
                <div class="login-wrapper">
                    <div class="loginbox">
                        <div class="img-logo">
                            <img src="../../../assets/img/logo.svg" class="img-fluid" alt="Logo">
                            <div class="back-home">
                                <a href="javascript:void(0);">Back to Home</a>
                            </div>
                        </div>
                        <h1>Enter Varification Code</h1>
                        <div class="reset-password">
                            <p>We have just sent a verification code to your registed email id</p>
                        </div>
                        <form action="login" class="verification-code">
                            <div class="row">
                                <div class="col-lg-12">
                                    <div class="d-flex digit-group">
                                        <input type="text" class="form-control" id="digit-1" name="digit-1" data-next="digit-2" value="8" />
                                        <input type="text" class="form-control" id="digit-2" name="digit-2" data-next="digit-3" data-previous="digit-1" />
                                        <input type="text" class="form-control" id="digit-3" name="digit-3" data-next="digit-4" data-previous="digit-2" />
                                        <input type="text"  class="form-control" id="digit-4" name="digit-4" data-next="digit-5" data-previous="digit-3" />
                                    </div>   
                                </div>
                                <div class="send-code">
                                    <router-link to="verification-code">Send the code again</router-link>
                                </div>
                                <div class="d-grid">
                                    <button class="btn btn-primary btn-start" type="submit">Submit</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
                <!-- /Login -->
                
            </div>
            
        </div>
    </div>
    <!-- /Main Wrapper -->
</template>
<script>
    import Vue from 'vue'
    export default {
      components: {
        
      },
      data() {
            return {
               
               
            }
        },
        mounted() {

            $('.digit-group').find('input').each(function() {
		$(this).attr('maxlength', 1);
			$(this).on('keyup', function(e) {
				var parent = $($(this).parent());
	
				if(e.keyCode === 8 || e.keyCode === 37) {
					var prev = parent.find('input#' + $(this).data('previous'));
					
					if(prev.length) {
						$(prev).select();
					}
				} else if((e.keyCode >= 48 && e.keyCode <= 57) || (e.keyCode >= 65 && e.keyCode <= 90) || (e.keyCode >= 96 && e.keyCode <= 105) || e.keyCode === 39) {
					var next = parent.find('input#' + $(this).data('next'));
					
					if(next.length) {
						$(next).select();
					} else {
						if(parent.data('autosubmit')) {
							parent.submit();
						}
					}
				}
			});
		});
	
		$('.digit-group input').on('keyup', function(){
			var self = $(this);
			if ( self.val() != '' ) {
				self.addClass('active');
			} else {
				self.removeClass('active');
			}
		});
        }
    }
</script>
