// angular/src/app/components/instructor/dashboard-instructor/dashboard-instructor.component.ts
import { Component, OnInit } from '@angular/core';
import { DataService } from 'src/app/shared/service/data/data.service';
import { routes } from 'src/app/shared/service/routes/routes';
@Component({
  selector: 'app-dashboard-instructor',
  templateUrl: './dashboard-instructor.component.html',
  styleUrls: ['./dashboard-instructor.component.scss']
})
export class DashboardInstructorComponent implements OnInit {
  public myCourse : any = [];
  public routes = routes;
 constructor(private DataService: DataService) {
    this.myCourse = this.DataService.myCourse;
    }

  ngOnInit(): void {
  }

}

<!-- Breadcrumb -->
<div class="page-banner instructor-bg-blk">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-lg-6 col-md-12">
                <div class="instructor-profile d-flex align-items-center">
                    <div class="instructor-profile-pic">
                        <a [routerLink]="routes.instructor_instructor_profile">
                            <img src="assets/img/instructor/profile-avatar.jpg" alt="" class="img-fluid">
                        </a>
                    </div>
                    <div class="instructor-profile-content">
                        <h4><a [routerLink]="routes.instructor_instructor_profile">Jenny Wilson <span>Beginner</span></a></h4>
                        <p>Instructor</p>
                    </div>
                </div>
            </div>
            <div class="col-lg-6 col-md-12">
                <div class="instructor-profile-menu">
                    <ul class="nav">
                        <li>
                            <div class="d-flex align-items-center">
                                <div class="instructor-profile-menu-img">
                                    <img src="assets/img/icon/icon-25.svg" alt="">
                                </div>
                                <div class="instructor-profile-menu-content">
                                    <h4>32</h4>
                                    <p>Courses</p>
                                </div>
                            </div>
                        </li>
                        <li>
                            <div class="d-flex align-items-center">
                                <div class="instructor-profile-menu-img">
                                    <img src="assets/img/icon/icon-26.svg" alt="">
                                </div>
                                <div class="instructor-profile-menu-content">
                                    <h4>11,604</h4>
                                    <p>Total Students</p>
                                </div>
                            </div>
                        </li>
                        <li>
                            <div class="d-flex align-items-center">
                                <div class="instructor-profile-menu-img">
                                    <img src="assets/img/icon/icon-27.svg" alt="">
                                </div>
                                <div class="instructor-profile-menu-content">
                                    <h4>12,230</h4>
                                    <p>Reviews</p>
                                </div>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="instructor-profile-text">
                    <p>I am an Innovation designer focussing on UX/UI based in Berlin. As a creative resident at Figma
                        explored the city of the future and how new technologies like AI, voice control, and augmented
                        reality will change our interfaces.</p>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- /Breadcrumb -->

<!-- Instructor Dashboard -->
<section class="page-content course-sec">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="card instructor-card">
                    <div class="card-header">
                        <h4>My Courses</h4>
                        <a [routerLink]="routes.page_add_course" class="btn btn-dark">Create New Course</a>
                    </div>
                    <div class="card-body">
                        <div class="instructor-grid" *ngFor="let data of myCourse">
                            <div class="product-img">
                                <a [routerLink]="routes.page_course_details">
                                    <img [src]="data.img1" class="img-fluid" alt="">
                                </a>
                            </div>
                            <div class="instructor-product-content">
                                <div class="head-course-title">
                                    <h3 class="title"><a [routerLink]="routes.page_course_details">{{data.content}}</a>
                                    </h3>
                                </div>
                                <div class="course-info d-flex align-items-center border-bottom-0 pb-0">
                                    <div class="rating-img d-flex align-items-center">
                                        <img [src]="data.img2" alt="">
                                        <p>{{data.lesson}}</p>
                                    </div>
                                    <div class="course-view d-flex align-items-center">
                                        <img [src]="data.img3" alt="">
                                        <p>{{data.time}}</p>
                                    </div>
                                </div>
                                <div class="rating mb-0">
                                    <i class="fas fa-star filled me-1"></i>
                                    <i class="fas fa-star filled me-1"></i>
                                    <i class="fas fa-star filled me-1"></i>
                                    <i class="fas fa-star filled me-1"></i>
                                    <i class="fas fa-star me-1"></i>
                                    <span class="d-inline-block average-rating"><span>{{data.rating}}</span>
                                        {{data.ratingNum}}</span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- /Instructor Dashboard -->

// vuejs/src/views/pages/instructor/dashboard-instructor.vue
<template>
    <!-- Main Wrapper -->
    <div class="main-wrapper">
        
        <layoutsinstructorborder></layoutsinstructorborder>
            <instructorbreadcrumb></instructorbreadcrumb>
            <!-- Instructor Dashboard -->
			<section class="page-content course-sec">
				<div class="container">
					<div class="row">  
						<div class="col-lg-12">
							<div class="card instructor-card">
								<div class="card-header">
									<h4>My Courses</h4>
									<router-link to="add-course" class="btn btn-dark">Create New Course</router-link>
								</div>
								<div class="card-body">
									<div class="instructor-grid">
										<div class="product-img">
											<router-link to="course-details">
												<img src="../../../assets/img/course/course-10.jpg" class="img-fluid" alt="">
                                            </router-link>
										</div>
										<div class="instructor-product-content">
											<div class="head-course-title">
												<h3 class="title"><router-link to="course-details">Information About UI/UX Design Degree</router-link></h3>
											</div>
											<div class="course-info d-flex align-items-center border-bottom-0 pb-0">
												<div class="rating-img d-flex align-items-center">
													<img src="../../../assets/img/icon/icon-01.svg" alt="">
													<p>12+ Lesson</p>
												</div>
												<div class="course-view d-flex align-items-center">
													<img src="../../../assets/img/icon/icon-02.svg" alt="">
													<p>9hr 30min</p>
												</div>
											</div>
											<div class="rating mb-0">							
												<i class="fas fa-star filled me-1"></i>
												<i class="fas fa-star filled me-1"></i>
												<i class="fas fa-star filled me-1"></i>
												<i class="fas fa-star filled me-1"></i>
												<i class="fas fa-star me-1"></i>
												<span class="d-inline-block average-rating"><span>4.0</span> (15)</span>
											</div>
										</div>
									</div>
									<div class="instructor-grid">
										<div class="product-img">
											<router-link to="course-details">
												<img src="../../../assets/img/course/course-11.jpg" class="img-fluid" alt="">
                                            </router-link>
										</div>
										<div class="instructor-product-content">
											<div class="head-course-title">
												<h3 class="title"><router-link to="course-details">Wordpress for Beginners - Master Wordpress Quickly</router-link></h3>
											</div>
											<div class="course-info d-flex align-items-center border-bottom-0 pb-0">
												<div class="rating-img d-flex align-items-center">
													<img src="../../../assets/img/icon/icon-01.svg" alt="">
													<p>10+ Lesson</p>
												</div>
												<div class="course-view d-flex align-items-center">
													<img src="../../../assets/img/icon/icon-02.svg" alt="">
													<p>7hr 20min</p>
												</div>
											</div>
											<div class="rating mb-0">							
												<i class="fas fa-star filled me-1"></i>
												<i class="fas fa-star filled me-1"></i>
												<i class="fas fa-star filled me-1"></i>
												<i class="fas fa-star filled me-1"></i>
												<i class="fas fa-star me-1"></i>
												<span class="d-inline-block average-rating"><span>4.2</span> (20)</span>
											</div>
										</div>
									</div>
									<div class="instructor-grid">
										<div class="product-img">
											<router-link to="course-details">
												<img src="../../../assets/img/course/course-12.jpg" class="img-fluid" alt="">
                                            </router-link>
										</div>
										<div class="instructor-product-content">
											<div class="head-course-title">
												<h3 class="title"><router-link to="course-details">Sketch from A to Z (2022): Become an app designer</router-link></h3>
											</div>
											<div class="course-info d-flex align-items-center border-bottom-0 pb-0">
												<div class="rating-img d-flex align-items-center">
													<img src="../../../assets/img/icon/icon-01.svg" alt="">
													<p>05+ Lesson</p>
												</div>
												<div class="course-view d-flex align-items-center">
													<img src="../../../assets/img/icon/icon-02.svg" alt="">
													<p>8hr 00min</p>
												</div>
											</div>
											<div class="rating mb-0">							
												<i class="fas fa-star filled me-1"></i>
												<i class="fas fa-star filled me-1"></i>
												<i class="fas fa-star filled me-1"></i>
												<i class="fas fa-star filled me-1"></i>
												<i class="fas fa-star me-1"></i>
												<span class="d-inline-block average-rating"><span>4.0</span> (10)</span>
											</div>
										</div>
									</div>
									<div class="instructor-grid">
										<div class="product-img">
											<router-link to="course-details">
												<img src="../../../assets/img/course/course-13.jpg" class="img-fluid" alt="">
                                            </router-link>
										</div>
										<div class="instructor-product-content">
											<div class="head-course-title">
												<h3 class="title"><router-link to="course-details">Learn Angular Fundamentals From beginning to advance lavel</router-link></h3>
											</div>
											<div class="course-info d-flex align-items-center border-bottom-0 pb-0">
												<div class="rating-img d-flex align-items-center">
													<img src="../../../assets/img/icon/icon-01.svg" alt="">
													<p>30+ Lesson</p>
												</div>
												<div class="course-view d-flex align-items-center">
													<img src="../../../assets/img/icon/icon-02.svg" alt="">
													<p>10hr 30min</p>
												</div>
											</div>
											<div class="rating mb-0">							
												<i class="fas fa-star filled me-1"></i>
												<i class="fas fa-star filled me-1"></i>
												<i class="fas fa-star filled me-1"></i>
												<i class="fas fa-star filled me-1"></i>
												<i class="fas fa-star me-1"></i>
												<span class="d-inline-block average-rating"><span>4.3</span> (25)</span>
											</div>
										</div>
									</div>
									<div class="instructor-grid">
										<div class="product-img">
											<router-link to="course-details">
												<img src="../../../assets/img/course/course-14.jpg" class="img-fluid" alt="">
                                            </router-link>
										</div>
										<div class="instructor-product-content">
											<div class="head-course-title">
												<h3 class="title"><router-link to="course-details">Build Responsive Real World Websites with HTML5 and CSS3</router-link></h3>
											</div>
											<div class="course-info d-flex align-items-center border-bottom-0 pb-0">
												<div class="rating-img d-flex align-items-center">
													<img src="../../../assets/img/icon/icon-01.svg" alt="">
													<p>20+ Lesson</p>
												</div>
												<div class="course-view d-flex align-items-center">
													<img src="../../../assets/img/icon/icon-02.svg" alt="">
													<p>7hr 00min</p>
												</div>
											</div>
											<div class="rating mb-0">							
												<i class="fas fa-star filled me-1"></i>
												<i class="fas fa-star filled me-1"></i>
												<i class="fas fa-star filled me-1"></i>
												<i class="fas fa-star filled me-1"></i>
												<i class="fas fa-star me-1"></i>
												<span class="d-inline-block average-rating"><span>4.0</span> (15)</span>
											</div>
										</div>
									</div>
									<div class="instructor-grid mb-0">
										<div class="product-img">
											<router-link to="course-details">
												<img src="../../../assets/img/course/course-15.jpg" class="img-fluid" alt="">
                                            </router-link>
										</div>
										<div class="instructor-product-content">
											<div class="head-course-title">
												<h3 class="title"><router-link to="course-details">C# Developers Double Your Coding Speed with Visual Studio</router-link></h3>
											</div>
											<div class="course-info d-flex align-items-center border-bottom-0 pb-0">
												<div class="rating-img d-flex align-items-center">
													<img src="../../../assets/img/icon/icon-01.svg" alt="">
													<p>50+ Lesson</p>
												</div>
												<div class="course-view d-flex align-items-center">
													<img src="../../../assets/img/icon/icon-02.svg" alt="">
													<p>10hr 30min</p>
												</div>
											</div>
											<div class="rating mb-0">							
												<i class="fas fa-star filled me-1"></i>
												<i class="fas fa-star filled me-1"></i>
												<i class="fas fa-star filled me-1"></i>
												<i class="fas fa-star filled me-1"></i>
												<i class="fas fa-star me-1"></i>
												<span class="d-inline-block average-rating"><span>4.5</span> (30)</span>
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>	
					</div>
				</div>
			</section>
			<!-- /Instructor Dashboard -->
        
        <layouts1></layouts1>
       
    </div>
    <!-- /Main Wrapper -->
</template>
